### PR TITLE
Delivery for Coordinate Conversion Addin DotNet V3 (Support)

### PR DESCRIPTION
**Pull request by saip**
This build addresses the GitHub tickets mentioned below:
- #532 - Coordinate Conversion ArcMap custom formatting not applied to MGRS, partially applied DDM
- #531 - Coordinate Conversion changing symbol for locations loses selection and location highlight
- #528 - Coordinate Conversion custom input format crashes Pro

### CODE REVIEW

**Comment by dfoll** [comment]
\Solutions\DefenseSolutions\CoordinateConversion\Testing\CTLocalGovTeam-dev\39 was built to test these changes

**Comment by dfoll** [comment]
This is still unmerged, waiting on #531

**Comment by saip** [comment]
Added a new commit to this pull request to fix the issue with #531

**Comment by dfoll** [comment]
\Solutions\DefenseSolutions\CoordinateConversion\Testing\CTLocalGovTeam-dev\42 was built to test this for merge

**Pull request merged**
