### PR TITLE
Delivery for Coordinate Conversion Addin DotNet V3 - Sprint 2

### PR DESCRIPTION
**Pull request by CTLocalGovTeam**
This build addresses the GitHub tickets mentioned below:

- #468 - Support the custom configuration of the DMS format of DD-MM-SS.SS
- #422 - User control of symbol
- #360 - User should be able to select a point on the map and have the point highlight in the list (ArcGIS Pro)
- #359 - User should be able to select a point on the map and have the point highlight in the list (ArcMap)
- #348 - Provide ability to format the Input coordinate (ArcMap)
- #347 - Provide ability to format the Input coordinate (ArcGIS Pro)

### CODE REVIEW

**Comment by dfoll** [comment]
@topowright  is there anything preventing us from checking this out and merging if good?

**Comment by lfunkhouser** [comment]
@topowright assigned. Please indicate if this cannot be reviewed and merged by 10 OCT 07:00. CT is awaiting sign-off for this functionality that had final delivery on 11 SEP.

**Comment by topowright** [comment]
@lfunkhouser  All capabilities have been implemented based on the information that we have given in the issues.

**Comment by lfunkhouser** [comment]
@topowright What has been implemented or changed that would result in the failure of testing on the build? If testing was completed on code that was merged into dev, indicate the build number that coincides with the tested functionality and whether it was tested on the component, Military Tools for ArcGIS or both.

**Comment by topowright** [comment]
Currently there is a challenge with the testing branch grabbing changes that were made in an identified branch. That is a Jenkins problem not a problem with Coordinate Conversion. I also experinced this with Military Symbol Editor last week. This is something I need to dig into further. 

The functionality was tested on build 18 of Coordinate Conversion and build 118 of Military Tools for ArcGIS. The functionality was tested in ArcMap and ArcGIS Pro

**Pull request merged**
