### PR TITLE
Delivery for Coordinate Conversion Addin DotNet V2 - Sprint 2 & Sprint 3

### PR DESCRIPTION
**Pull request by CTLocalGovTeam**
This build addresses the GitHub tickets mentioned below:
#492 - Export all coordinate types from the output section to feature class
#493 - Export all coordinate types from the output section to Shapefile
#495 - Export all coordinate types from the output section to KMZ

### CODE REVIEW

**Comment by CTLocalGovTeam** [comment]
Added Commit for Sprint 3 delivery 
#409 - Export to KMZ

**Comment by topowright** [comment]
checking the above issue again.

**Comment by topowright** [comment]
### Approved with no changes: 
#492 - Export all coordinate types from the output section to feature class

### Merging but expecting changes based on missing outputs
#493 - Export all coordinate types from the output section to Shapefile
#495 - Export all coordinate types from the output section to KMZ

Any custom name does not get picked up

**Comment by topowright** [comment]
The issue seems to be related to when a user is using a space or special character in the name the attribute information is dropped.

**Pull request merged**
